force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Project Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Description_tal__c.field-meta.xml
<CustomField>
    <fullName>Description_tal__c</fullName>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/EndDate_d__c.field-meta.xml
<CustomField>
    <fullName>EndDate_d__c</fullName>
    <label>EndDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Name_t__c.field-meta.xml
<CustomField>
    <fullName>Name_t__c</fullName>
    <label>Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/StartDate_d__c.field-meta.xml
<CustomField>
    <fullName>StartDate_d__c</fullName>
    <label>StartDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/TechStack_mp__c.field-meta.xml
<CustomField>
    <fullName>TechStack_mp__c</fullName>
    <label>Tech Stack</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Node.js</fullName>
            </value>
            <value>
                <fullName>Express.js</fullName>
            </value>
            <value>
                <fullName>Salesforce Apex</fullName>
            </value>
            <value>
                <fullName>Salesforce LWC</fullName>
            </value>
            <value>
                <fullName>Salesforce REST API</fullName>
            </value>
            <value>
                <fullName>JavaScript (ES6+)</fullName>
            </value>
            <value>
                <fullName>HTML5</fullName>
            </value>
            <value>
                <fullName>CSS3</fullName>
            </value>
            <value>
                <fullName>MongoDB</fullName>
            </value>
            <value>
                <fullName>PostgreSQL</fullName>
            </value>
            <value>
                <fullName>Git &amp; GitHub</fullName>
            </value>
            <value>
                <fullName>Heroku</fullName>
            </value>
            <value>
                <fullName>Render.com</fullName>
            </value>
            <value>
                <fullName>OAuth 2.0</fullName>
            </value>
            <value>
                <fullName>Mocha &amp; Chai</fullName>
            </value>
            <value>
                <fullName>Webpack</fullName>
            </value>
            <value>
                <fullName>Jenkins (CI/CD)</fullName>
            </value>
            <value>
                <fullName>Docker</fullName>
            </value>
            <value>
                <fullName>Salesforce CLI</fullName>
            </value>
            <value>
                <fullName>Visual Studio Code</fullName>
            </value>
            <value>
                <fullName>Salesforce Flows</fullName>
            </value>
            <value>
                <fullName>Process Builder</fullName>
            </value>
            <value>
                <fullName>Email Alerts</fullName>
            </value>
            <value>
                <fullName>Objects &amp; Fields</fullName>
            </value>
            <value>
                <fullName>Validation Rules</fullName>
            </value>
            <value>
                <fullName>Formula Fields</fullName>
            </value>
            <value>
                <fullName>Managed Packages</fullName>
            </value>
            <value>
                <fullName>Reports &amp; Dashboards</fullName>
            </value>
            <value>
                <fullName>SBQQ CPQ</fullName>
            </value>
            <value>
                <fullName>React</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/URL_url__c.field-meta.xml
<CustomField>
    <fullName>URL_url__c</fullName>
    <label>URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/ProjectService.cls
public without sharing class ProjectService {
    
    public static List<ProjectWrapper> getAllProjects() {
        List<ProjectWrapper> projectList = new List<ProjectWrapper>();
        for (Project__c p : [SELECT Id, Name, Name_t__c, Description_tal__c, StartDate_d__c, EndDate_d__c, TechStack_mp__c, URL_url__c FROM Project__c ORDER BY EndDate_d__c DESC NULLS FIRST]) {
            projectList.add(new ProjectWrapper(p));
        }
        return projectList;
    }

    public static ProjectWrapperExtended getProjectByUUID(String uuid) {
        List<Project__c> projectList = [SELECT Id, Name, Name_t__c, Description_tal__c, StartDate_d__c, EndDate_d__c, TechStack_mp__c, URL_url__c FROM Project__c WHERE Name =:uuid];
        if (projectList.isEmpty()) {
            throw new GeneralException('Project not found with UUID: ' + uuid, 404);
        }
        return new ProjectWrapperExtended(projectList[0]);
    }
    
    public static Set<String> getAllSkills() {
        Set<String> skills = new Set<String>();
        for (Project__c p : [SELECT Id, toLabel(TechStack_mp__c) FROM Project__c ORDER BY EndDate_d__c DESC NULLS FIRST]) {
            if (String.isNotBlank(p.TechStack_mp__c))
            	skills.addAll(p.TechStack_mp__c.split(';'));
        }
        return skills;
    }
    
    public virtual class ProjectWrapper {
        public String name;
        public String start_date;
        public String end_date;
        public String descrption;
        public String uuid;
        public String more_info;
        private ProjectWrapper(Project__c p) {
            uuid = p.Name;
            name = p.Name_t__c;
            descrption = p.Description_tal__c;
            more_info = p.URL_url__c;
            start_date = Utility.toMonthAndYear(p.StartDate_d__c);
            end_date = Utility.toMonthAndYear(p.EndDate_d__c);
        }
    }

    public class ProjectWrapperExtended extends ProjectWrapper{
        public List<String> tech_stack;
        private ProjectWrapperExtended(Project__c p) {
            super(p);
            tech_stack = String.isNotBlank(p.TechStack_mp__c) ? p.TechStack_mp__c.split(';') : new List<String>();
        }
    }
    
}