force-app/main/default/objects/Certification__c/Certification__c.object-meta.xml
<CustomObject>
    <label>Certification</label>
    <nameField>
        <displayFormat>CRT-{00000}</displayFormat>
        <label>Certification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Certifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Certification__c/fields/BadgeName_t__c.field-meta.xml
<CustomField>
    <fullName>BadgeName_t__c</fullName>
    <label>Badge Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Certification__c/fields/IssuedOn_d__c.field-meta.xml
<CustomField>
    <fullName>IssuedOn_d__c</fullName>
    <label>Issued On</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Certification__c/fields/Title_t__c.field-meta.xml
<CustomField>
    <fullName>Title_t__c</fullName>
    <label>Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CertificationService.cls
public without sharing class CertificationService {
    public static string SITE_URL = 'https://personalproject6-dev-ed.develop.my.salesforce-sites.com/api/resource/' + DateTime.now().getTime() + '/badges/';
    public static List<CertWrapper> getAllCerts() {
        List<CertWrapper> wpList = new List<CertWrapper>();
        for (Certification__c c : [SELECT Id, Title_t__c, BadgeName_t__c, IssuedOn_d__c FROM Certification__c ORDER BY IssuedOn_d__c DESC]) {
            wpList.add(new CertWrapper(c));
        }
        return wpList;
    }
    public class CertWrapper {
        public String title;
        public String badge_url;
        public String issued_date;
        
        public CertWrapper(Certification__c a) {
            title = a.Title_t__c;
            issued_date = a.IssuedOn_d__c == null ? '' : Utility.toMonthAndYear(a.IssuedOn_d__c);
            badge_url = String.isNotBlank(a.BadgeName_t__c) ? SITE_URL + a.BadgeName_t__c : '';
        }
    }
}