force-app/main/default/objects/Path__c/Path__c.object-meta.xml
<CustomObject>
    <label>Path</label>
    <nameField>
        <displayFormat>P-{00000}</displayFormat>
        <label>Path Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Paths</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Path__c/fields/Body__c.field-meta.xml
<CustomField>
    <fullName>Body__c</fullName>
    <defaultValue>&apos;{}&apos;</defaultValue>
    <label>Body</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Path__c/fields/ContentType__c.field-meta.xml
<CustomField>
    <fullName>ContentType__c</fullName>
    <label>Content Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>application/json</fullName>
                <default>true</default>
                <label>application/json</label>
            </value>
            <value>
                <fullName>application/xml</fullName>
            </value>
            <value>
                <fullName>text/plain</fullName>
            </value>
            <value>
                <fullName>text/html</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Path__c/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <label>Method</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GET</fullName>
                <default>true</default>
                <label>GET</label>
            </value>
            <value>
                <fullName>POST</fullName>
            </value>
            <value>
                <fullName>PATCH</fullName>
            </value>
            <value>
                <fullName>PUT</fullName>
            </value>
            <value>
                <fullName>DELETE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Path__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <label>Resource</label>
    <referenceTo>Resource__c</referenceTo>
    <relationshipLabel>Paths</relationshipLabel>
    <relationshipName>Paths</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Path__c/fields/StatusCode__c.field-meta.xml
<CustomField>
    <fullName>StatusCode__c</fullName>
    <label>Status Code</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>200</fullName>
                <default>true</default>
                <label>200 OK</label>
            </value>
            <value>
                <fullName>201</fullName>
                <label>201 CREATED</label>
            </value>
            <value>
                <fullName>202</fullName>
                <label>202 ACCEPTED</label>
            </value>
            <value>
                <fullName>204</fullName>
                <label>204 NO_CONTENT</label>
            </value>
            <value>
                <fullName>206</fullName>
                <label>206 PARTIAL_CONTENT</label>
            </value>
            <value>
                <fullName>300</fullName>
                <label>300 MULTIPLE_CHOICES</label>
            </value>
            <value>
                <fullName>301</fullName>
                <label>301 MOVED_PERMANENTLY</label>
            </value>
            <value>
                <fullName>302</fullName>
                <label>302 FOUND</label>
            </value>
            <value>
                <fullName>304</fullName>
                <label>304 NOT_MODIFIED</label>
            </value>
            <value>
                <fullName>400</fullName>
                <label>400 BAD_REQUEST</label>
            </value>
            <value>
                <fullName>401</fullName>
                <label>401 UNAUTHORIZED</label>
            </value>
            <value>
                <fullName>403</fullName>
                <label>403 FORBIDDEN</label>
            </value>
            <value>
                <fullName>404</fullName>
                <label>404 NOT_FOUND</label>
            </value>
            <value>
                <fullName>405</fullName>
                <label>405 METHOD_NOT_ALLOWED</label>
            </value>
            <value>
                <fullName>406</fullName>
                <label>406 NOT_ACCEPTABLE</label>
            </value>
            <value>
                <fullName>409</fullName>
                <label>409 CONFLICT</label>
            </value>
            <value>
                <fullName>410</fullName>
                <label>410 GONE</label>
            </value>
            <value>
                <fullName>412</fullName>
                <label>412 PRECONDITION_FAILED</label>
            </value>
            <value>
                <fullName>413</fullName>
                <label>413 REQUEST_ENTITY_TOO_LARGE</label>
            </value>
            <value>
                <fullName>414</fullName>
                <label>414 REQUEST_URI_TOO_LARGE</label>
            </value>
            <value>
                <fullName>415</fullName>
                <label>415 UNSUPPORTED_MEDIA_TYPE</label>
            </value>
            <value>
                <fullName>417</fullName>
                <label>417 EXPECTATION_FAILED</label>
            </value>
            <value>
                <fullName>500</fullName>
                <label>500 INTERNAL_SERVER_ERROR</label>
            </value>
            <value>
                <fullName>503</fullName>
                <label>503 SERVER_UNAVAILABLE</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Resource__c/Resource__c.object-meta.xml
<CustomObject>
    <label>Resource</label>
    <nameField>
        <label>Resource Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Resource__c/fields/APIKey__c.field-meta.xml
<CustomField>
    <fullName>APIKey__c</fullName>
    <label>API Key</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Resource__c/fields/AppID__c.field-meta.xml
<CustomField>
    <fullName>AppID__c</fullName>
    <label>App ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Resource__c/fields/ContactEmail__c.field-meta.xml
<CustomField>
    <fullName>ContactEmail__c</fullName>
    <label>Contact Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Resource__c/fields/RequestURL__c.field-meta.xml
<CustomField>
    <fullName>RequestURL__c</fullName>
    <formula>$Label.BaseURL  +  AppID__c + &apos;/&apos;</formula>
    <label>RequestURL</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MockAPIResourceController.cls
public without sharing class MockAPIResourceController {
    
    @AuraEnabled
    public static Resource__c getResource(String appId){
        Resource__c resource;
        try {
            for (resource__c r : [SELECT ID, Name, AppID__c, Description__c, RequestURL__c, ContactEmail__c, ApiKey__c,
                    (SELECT Id, Name, Path__c, Method__c, ContentType__c, Body__c, 
                        StatusCode__c, Resource__c, Resource__r.RequestURL__c 
                        FROM Paths__r ORDER BY CreatedDate DESC)
                    FROM Resource__c WHERE AppID__c = :appId LIMIT 1]) {
                resource = r;
            }
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
        return resource;
    }
    
    @AuraEnabled
    public static Resource__c upsertResource(Resource__c resource){
        try {
            upsert resource;
            for (resource__c r : [SELECT ID, Name, AppID__c, Description__c, RequestURL__c, ContactEmail__c, ApiKey__c,
                    (SELECT Id, Name, Path__c, Method__c, ContentType__c, Body__c, 
                        StatusCode__c, Resource__c, Resource__r.RequestURL__c 
                        FROM Paths__r ORDER BY CreatedDate DESC)
                    FROM Resource__c WHERE Id = :resource.Id LIMIT 1]) {
                resource = r;
            }
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
        return resource;
    }
    
    @AuraEnabled(cacheable=true)
    public static List<Resource__c> getResourcesByEmail(String email){
        try {
            return [SELECT ID, Name, AppID__c, Description__c, RequestURL__c, ContactEmail__c, APIKey__c FROM Resource__c WHERE ContactEmail__c = :email ORDER BY CreatedDate DESC LIMIT 50];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static void deleteResource(Id resourceId){
        try {
            delete new Resource__c(Id = resourceId);
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    
}