force-app/main/default/objects/Path__c/Path__c.object-meta.xml
<CustomObject>
    <label>Path</label>
    <nameField>
        <displayFormat>P-{00000}</displayFormat>
        <label>Path Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Paths</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Path__c/fields/Body__c.field-meta.xml
<CustomField>
    <fullName>Body__c</fullName>
    <defaultValue>&apos;{}&apos;</defaultValue>
    <label>Body</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Path__c/fields/ContentType__c.field-meta.xml
<CustomField>
    <fullName>ContentType__c</fullName>
    <label>Content Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>application/json</fullName>
                <default>true</default>
                <label>application/json</label>
            </value>
            <value>
                <fullName>application/xml</fullName>
            </value>
            <value>
                <fullName>text/plain</fullName>
            </value>
            <value>
                <fullName>text/html</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Path__c/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <label>Method</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GET</fullName>
                <default>true</default>
                <label>GET</label>
            </value>
            <value>
                <fullName>POST</fullName>
            </value>
            <value>
                <fullName>PATCH</fullName>
            </value>
            <value>
                <fullName>PUT</fullName>
            </value>
            <value>
                <fullName>DELETE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Path__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <label>Resource</label>
    <referenceTo>Resource__c</referenceTo>
    <relationshipLabel>Paths</relationshipLabel>
    <relationshipName>Paths</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Path__c/fields/StatusCode__c.field-meta.xml
<CustomField>
    <fullName>StatusCode__c</fullName>
    <label>Status Code</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>200</fullName>
                <default>true</default>
                <label>200 OK</label>
            </value>
            <value>
                <fullName>201</fullName>
                <label>201 CREATED</label>
            </value>
            <value>
                <fullName>202</fullName>
                <label>202 ACCEPTED</label>
            </value>
            <value>
                <fullName>204</fullName>
                <label>204 NO_CONTENT</label>
            </value>
            <value>
                <fullName>206</fullName>
                <label>206 PARTIAL_CONTENT</label>
            </value>
            <value>
                <fullName>300</fullName>
                <label>300 MULTIPLE_CHOICES</label>
            </value>
            <value>
                <fullName>301</fullName>
                <label>301 MOVED_PERMANENTLY</label>
            </value>
            <value>
                <fullName>302</fullName>
                <label>302 FOUND</label>
            </value>
            <value>
                <fullName>304</fullName>
                <label>304 NOT_MODIFIED</label>
            </value>
            <value>
                <fullName>400</fullName>
                <label>400 BAD_REQUEST</label>
            </value>
            <value>
                <fullName>401</fullName>
                <label>401 UNAUTHORIZED</label>
            </value>
            <value>
                <fullName>403</fullName>
                <label>403 FORBIDDEN</label>
            </value>
            <value>
                <fullName>404</fullName>
                <label>404 NOT_FOUND</label>
            </value>
            <value>
                <fullName>405</fullName>
                <label>405 METHOD_NOT_ALLOWED</label>
            </value>
            <value>
                <fullName>406</fullName>
                <label>406 NOT_ACCEPTABLE</label>
            </value>
            <value>
                <fullName>409</fullName>
                <label>409 CONFLICT</label>
            </value>
            <value>
                <fullName>410</fullName>
                <label>410 GONE</label>
            </value>
            <value>
                <fullName>412</fullName>
                <label>412 PRECONDITION_FAILED</label>
            </value>
            <value>
                <fullName>413</fullName>
                <label>413 REQUEST_ENTITY_TOO_LARGE</label>
            </value>
            <value>
                <fullName>414</fullName>
                <label>414 REQUEST_URI_TOO_LARGE</label>
            </value>
            <value>
                <fullName>415</fullName>
                <label>415 UNSUPPORTED_MEDIA_TYPE</label>
            </value>
            <value>
                <fullName>417</fullName>
                <label>417 EXPECTATION_FAILED</label>
            </value>
            <value>
                <fullName>500</fullName>
                <label>500 INTERNAL_SERVER_ERROR</label>
            </value>
            <value>
                <fullName>503</fullName>
                <label>503 SERVER_UNAVAILABLE</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Resource__c/Resource__c.object-meta.xml
<CustomObject>
    <label>Resource</label>
    <nameField>
        <label>Resource Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Resource__c/fields/APIKey__c.field-meta.xml
<CustomField>
    <fullName>APIKey__c</fullName>
    <label>API Key</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Resource__c/fields/AppID__c.field-meta.xml
<CustomField>
    <fullName>AppID__c</fullName>
    <label>App ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/MockAPIWebService.cls
@RestResource (urlMapping='/api/*/*')
global without sharing class MockAPIWebService {
    
    @HttpGet
    global static void doGet() {
        respond();
    }
    
    @HttpPost
    global static void doPost() {
        respond();
    }
    
    @HttpPut
    global static void doPut() {
        respond();
    }
    
    @HttpDelete
    global static void doDelete() {
        respond();
    }
    
    @HttpPatch
    global static void doPatch() {
        respond();
    }
    
    private static void respond() {
        try {
            new MockResource(RestContext.request, RestContext.response).respond();
        } catch (Exception e) {
            if (e instanceOf GeneralException) {
                Utility.sendErrorResponse((GeneralException)e);
            } else {
                Utility.sendErrorResponse(e);
            }
        }
    }
    
    public without sharing class MockResource {
        public String appId { get; private set; }
        public String subpath { get; private set; }
        public String apiKey { get; private set; }
        public String method { get; private set; }
        public RestResponse res { get; private set; }
        private Resource__c resource;
        
        public MockResource(RestRequest req, RestResponse res) {
            List<String> pathParts = req.requestURI.replace('/api/', '').split('/');
            if (pathParts.size() > 0) {
                appId = pathParts[0];
                pathParts.remove(0);
            }
            if (pathParts.size() > 0) {
                subpath = String.join(pathParts, '/');
            }
            method = req.httpMethod;
            this.res = res;
            apiKey = extractApiKey(req);
            validate();
        }
        
        private String extractApiKey(RestRequest req) {
            List<String> headerKeys = new List<String>{'x-api-key', 'X-API-Key', 'X-API-KEY'};
            List<String> paramKeys = new List<String>{'apiKey', 'apikey'};
            
            for (String key : headerKeys) {
                if (req.headers.containsKey(key)) {
                    return req.headers.get(key);
                }
            }
            
            for (String key : paramKeys) {
                if (req.params.containsKey(key)) {
                    return req.params.get(key);
                }
            }
            
            return null;
        }
        
        private void validate() {
            for (Resource__c r : [SELECT Id, Name, APIKey__c FROM Resource__c WHERE AppID__c = :appId LIMIT 1]) {
                resource = r;
            }
            if (resource == null) {
                throw new GeneralException(Label.NotFound, Constants.HTTP_NOT_FOUND);
            }
            if (String.isNotBlank(resource.APIKey__c) && resource.APIKey__c != apiKey) {
                throw new GeneralException(Label.Unauthorised, Constants.HTTP_UNAUTHORIZED);
            }
        }
        
        public void respond() {
            if (String.isBlank(subpath)) {
                Utility.sendSuccessResponse(String.format(Label.NoSubpath, new List<String>{Label.BaseURL.replace('/services/apexrest/api/', '/s/resource?appId=' + appId)}));
                return;
            }
            Boolean isSubpathValid = false;
            for (Path__c p : [SELECT Id, Name, Path__c, Method__c, ContentType__c, Body__c, StatusCode__c FROM Path__c WHERE Resource__c = :resource.Id AND Path__c = :subpath]) {
                isSubpathValid = true;
                if (p.Method__c == method) {
                    setResponse(p, res);
                    return;
                }
            }
            if (isSubpathValid) {
                Utility.sendErrorResponse(Label.InvalidMethod, Constants.HTTP_NOT_ALLOWED);
            } else {
                Utility.sendErrorResponse(Label.NotFound, Constants.HTTP_NOT_FOUND);
            }
        }
        
        public void setResponse(Path__c path, RestResponse res) {
            if (String.isNotBlank(path.Body__c)) {
                res.responseBody = Blob.valueOf(path.Body__c);
            }
            res.statusCode = Integer.valueOf(path.StatusCode__c);
            if (String.isNotBlank(path.ContentType__c)) {
                res.addHeader('Content-Type', path.ContentType__c);
            } else {
                res.addHeader('Content-Type', 'application/json');
            }
        }
    }
    
}