force-app/main/default/objects/Resource__c/Resource__c.object-meta.xml
<CustomObject>
    <label>Resource</label>
    <nameField>
        <label>Resource Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Resource__c/fields/APIKey__c.field-meta.xml
<CustomField>
    <fullName>APIKey__c</fullName>
    <label>API Key</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Resource__c/fields/AppID__c.field-meta.xml
<CustomField>
    <fullName>AppID__c</fullName>
    <label>App ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Resource__c/fields/ContactEmail__c.field-meta.xml
<CustomField>
    <fullName>ContactEmail__c</fullName>
    <label>Contact Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Resource__c/fields/RequestURL__c.field-meta.xml
<CustomField>
    <fullName>RequestURL__c</fullName>
    <formula>$Label.BaseURL  +  AppID__c + &apos;/&apos;</formula>
    <label>RequestURL</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MockAPIResourceContoller.cls
public without sharing class MockAPIResourceContoller {
    
    @AuraEnabled
    public static Resource__c getResource(String appId){
        Resource__c resource = new Resource__c();
        try {
            for (resource__c r : [SELECT ID, Name, AppID__c, Description__c, RequestURL__c, ContactEmail__c, ApiKey__c FROM Resource__c WHERE AppID__c = :appId LIMIT 1]) {
                resource = r;
            }
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
        return resource;
    }
    
    @AuraEnabled
    public static Resource__c upsertResource(Resource__c resource){
        try {
            upsert resource;
            for (resource__c r : [SELECT ID, Name, AppID__c, Description__c, RequestURL__c, ContactEmail__c, APIKey__c FROM Resource__c WHERE Id = :resource.Id LIMIT 1]) {
                resource = r;
            }
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
        return resource;
    }

    @AuraEnabled(cacheable=true)
    public static List<Resource__c> getResourcesByEmail(String email){
        try {
            return [SELECT ID, Name, AppID__c, Description__c, RequestURL__c, ContactEmail__c, APIKey__c FROM Resource__c WHERE ContactEmail__c = :email ORDER BY CreatedDate DESC LIMIT 50];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

}